### ISSUE TITLE
Implement password hashing with bcrypt

### ISSUE THREAD

**Issue by MungaSoftwiz** [MungaSoftwiz/org-authenticator-api#12]
We need to enhance the security of our application by implementing password hashing. The bcrypt package is a secure way to hash passwords. Integrate this in our user authentication flow.

**Tasks:**

- [x] Create password hashing function.
- [x] Create password verification function.
- [x] Integrate password hashing in registration flow:
