### ISSUE TITLE
Update user registration endpoint

### ISSUE THREAD

**Issue by MungaSoftwiz** [MungaSoftwiz/org-authenticator-api#14]
Update the user registration endpoint, including reading JSON data from the request, validating the payload, and returning appropriate responses.

**Tasks:**

- [x] Read JSON payload from the request.
- [x] Validate payload using the validator package.
- [x] Return a 400 Bad Request response if JSON reading or validation fails.
