### ISSUE TITLE
Refactor to use sqlx intead of sql

### ISSUE THREAD

**Issue by MungaSoftwiz** [MungaSoftwiz/org-authenticator-api#15]
Refactor the code to use `sqlx` instead of `sql` for database interactions. `sqlx` provides an extension to `database/sql` that includes useful features for working with databases in Go, such as struct scanning and named query support, making database operations more convenient and less error-prone.

**Tasks:**

- [x] Update the APIServer struct to use `*sqlx.DB` instead of `*sql.DB`.
- [x] Initialize APIServer using `*sqlx.DB`.
- [x] Ensure server is running with sqlx integration.
