### ISSUE TITLE
Implement PostgreSQL database connection

### ISSUE THREAD

**Issue by MungaSoftwiz** [MungaSoftwiz/org-authenticator-api#4]
**Description:**

Create a function to initialise and connect to the PostgreSQL database. Ensure the connection is established by pinging the database.

**Tasks**

- [x] Implement a function in that creates a PostgreSQL connection.
- [x] Connect to the database using the provided configuration.
- [x] Verify the connection.
